version: '2'

services:
  db:
    image: mysql
    container_name: db-stock-projet
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-stock-projet
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev
  
  maildev:
    image: maildev/maildev
    container_name: maildev-stock-projet
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    restart: always
    ports:
      - 8081:80
    networks:
      - dev
  www:
    build: docker
    container_name: www-stock-projet
    ports:
      - "8082:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev
      
networks:
  dev:


    